services:
  postgres:
    image: postgres:18
    container_name: webparser_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webparser
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webparser_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: webparser_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
    entrypoint: >
      /bin/sh -c "
      chmod 600 /pgpass;
      /entrypoint.sh
      "
    depends_on:
      - postgres
    networks:
      - webparser_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webparser_api
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8090:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=webparser;Username=postgres;Password=postgres"
    command: dotnet watch run --no-launch-profile
    depends_on:
      - postgres
    networks:
      - webparser_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  webparser_network:
    driver: bridge